name: Run main.py

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight (12:00 AM) every day

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12" # Latest stable version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --local user.email "114857078+SantiagoRR2004@users.noreply.github.com"
          git config --local user.name "SantiagoRR2004"
          if ! git diff --quiet; then
            git add .
            git commit -m "chore: Update README.md [GitHub Action]"
            git push
          else
            echo "No changes to push."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
