name: Run main.py

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight (12:00 AM) every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12" # Latest stable version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
