name: Remove README.md history

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 31 12 *'  # 12:00 UTC on December 31

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Required for BFG to work on full history

      - name: Remove README.md history
        run: |
          LATEST_VERSION=$(curl -s https://repo1.maven.org/maven2/com/madgag/bfg/maven-metadata.xml | grep '<latest>' | sed -E 's/.*<latest>(.*)<\/latest>.*/\1/')
          curl -L "https://repo1.maven.org/maven2/com/madgag/bfg/${LATEST_VERSION}/bfg-${LATEST_VERSION}.jar" -o bfg.jar
          java -jar bfg.jar --delete-files README.md
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive

      - name: Push changes
        run: |
          git config --local user.email "${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com"
          git config --local user.name "${{ github.repository_owner }}"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove empty commits
        run: |
          FILTER_BRANCH_SQUELCH_WARNING=1 git filter-branch --commit-filter 'git_commit_non_empty_tree "$@"' -f HEAD
          rm -rf .git/refs/original/
          git reflog expire --all
          git gc --aggressive --prune

      - name: Push changes 2
        run: |
          git config --local user.email "${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com"
          git config --local user.name "${{ github.repository_owner }}"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
